# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/comics',
                'doc_host': 'https://riversdark.github.io',
                'git_url': 'https://github.com/riversdark/comics',
                'lib_path': 'comics'},
  'syms': { 'comics.core': {'comics.core.foo': ('core.html#foo', 'comics/core.py')},
            'comics.iam': {},
            'comics.ump': {'comics.ump.process_files': ('ump.html#process_files', 'comics/ump.py')}}}