# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/comics',
                'doc_host': 'https://riversdark.github.io',
                'git_url': 'https://github.com/riversdark/comics',
                'lib_path': 'comics'},
  'syms': { 'comics.core': {'comics.core.foo': ('core.html#foo', 'comics/core.py')},
            'comics.iam': { 'comics.iam.explore_mzml_file': ('iam.html#explore_mzml_file', 'comics/iam.py'),
                            'comics.iam.explore_mzxml_file': ('iam.html#explore_mzxml_file', 'comics/iam.py'),
                            'comics.iam.generate_feature_maps': ('iam.html#generate_feature_maps', 'comics/iam.py'),
                            'comics.iam.mzxml_to_mzml': ('iam.html#mzxml_to_mzml', 'comics/iam.py')},
            'comics.ump': {'comics.ump.process_files': ('ump.html#process_files', 'comics/ump.py')}}}
